### ISSUE TITLE
Can I change the Return Label size other than A4?

### ISSUE THREAD

**Issue by ericknyoto** [netresearch/dhl-sdk-api-bcs-returns#1]
Hello,
Can I change the Return Label size other than A4? Because I wanted to print on a label printer with size 103 x 199 mm.

Thanks!

**Comment by mam08ixo** [comment]
The label size cannot be configured via web service request / this API SDK.

The vendor FAQ contains a page [How can I configure the label printing size / paper format? ](https://dhl.support.netresearch.de/support/solutions/articles/12000045908-how-can-i-configure-the-label-printing-size-paper-format-)

Please check if that solution does not only apply for shipping labels but also for return labels.
