### ISSUE TITLE
$receiverId is 3 digits lowercase

### ISSUE THREAD

**Issue by flowl** [netresearch/dhl-sdk-api-bcs-returns#3]
According to https://entwickler.dhl.de/group/ep/wsapis/retouren/authentifizierung
the receiverID is not `DE` but `deu`:

Absendeland | Retourenempfängername (receiverID)
-- | --
Belgien | bel
Bulgarien | bgr
Dänemark | dnk
Deutschland | deu
....

**Comment by moehrenzahn** [comment]
Hi flowl, thanks for that!

You are correct, this was recently changed at the DHL API. We will correct this in our README in the next release of this package.

**Comment by moehrenzahn** [comment]
Until then, this should in no way affect the actual functionality of the SDK. It's "just" a misleading example in the readme.

**Comment by flowl** [comment]
Hi Max @moehrenzahn ,
I was misinterpreting the `receiverID` in the manual.
The value that has to be used is listed in the Geschäftskundenportal.

What has actually changed is the country code in the ShipperAddress, which must be 3-digits now.

    $requestBuilder->setShipperAddress();

**Comment by moehrenzahn** [comment]
You are right! We will correct this in our README in the next release of this package as well.

Thanks for your feedback!
