### ISSUE TITLE
Undefined index: qrLabelData for international return labels

### ISSUE THREAD

**Issue by ddpfl** [netresearch/dhl-sdk-api-bcs-returns#6]
I am receiving the following error when using the SDK to create a return label:

> Undefined index: qrLabelData in vendor/dhl/sdk-api-bcs-returns/src/Service/ReturnLabelService.php on line 92

So far I received this error while creating a return label for Spain and Finland. I am not sure how many other countries are affected. The line in question:

`$qrLabelData = $responseData['qrLabelData'] ?: '';`

should probably be:

`$qrLabelData = $responseData['qrLabelData'] ?? '';`

since it seems the qrLabelData key can be missing entirely. I was able to reproduce this error for both the sandbox and the live API.

**Comment by mam08ixo** [comment]
Thank you for reporting the issue. I can confirm that the `qrLabelData` is no longer present for other countries, too. Previously it was included in the response with a value of `null`. We will prepare a bugfix version accordingly.

**Comment by powli** [comment]
_Internal reference: DHLGW-1252_
