### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by zeitlersensetence** [netresearch/dhl-sdk-api-bcs-returns#7]
Please add PHP 8.1 support

**Comment by mam08ixo** [comment]
@zeitlersensetence I do not see how we could add PHP 8.1 support to a PHP 8.1 compatible package. What exactly are you missing?

**Comment by zeitlersensetence** [comment]
The Problem is that the composer.json is fixed to php 8.0.x, not allowing to install the package with php 8.1.x running...

**Comment by mam08ixo** [comment]
No, it's not. Please read the [Composer documentation](https://getcomposer.org/doc/articles/versions.md#caret-version-range-) to understand version constraints.

**Comment by zeitlersensetence** [comment]
okey, if you want you can close the issue...we were not able to install it, saying it is not compatible with php 8.1.

**Comment by zeitlersensetence** [comment]
FYI  Problem 1
    - dhl/sdk-api-bcs-returns 1.0.0 requires php ^7.0.0 -> your php version (8.1
.15) does not satisfy that requirement.

**Comment by mam08ixo** [comment]
Why are you attempting to install a very old version of the package?

**Comment by zeitlersensetence** [comment]
what I do is exacly this: composer require dhl/sdk-api-bcs-returns

**Comment by zeitlersensetence** [comment]
is it possible, that we have to install it from git repository, because composer package repository was not updated yet and is still 1.0.0? I tried to install it with version set to 2.1.1 via composer

Could not find a matching version of package dhl/sdk-api-bcs-returns@2.1.1.

**Comment by mam08ixo** [comment]
The Composer package repository is up-to-date: https://packagist.org/packages/dhl/sdk-api-bcs-returns#2.1.1

Unless you disabled it in your project, I do not see a reason why it cannot be found in the latest version.

**Comment by zeitlersensetence** [comment]
very strange 😢  I'll have another try...should be working somehow. Thanks

**Comment by mam08ixo** [comment]
Okay, that means you had some of the library's dependencies already installed in older versions that did only match the v1.0.0 constraints. Glad you figured it out 👍
