### ISSUE TITLE
ReturnLabelErrorPlugin::createErrorMessage() must be of the type array, null given

### ISSUE THREAD

**Issue by cottton** [netresearch/dhl-sdk-api-bcs-returns#9]
Using version `2.0.1` atm, but seems to be the same code in master.

**Error:**

    Argument 1 passed to Dhl\Sdk\Paket\Retoure\Http\ClientPlugin\ReturnLabelErrorPlugin::createErrorMessage() must be of the type array, null given, called in /var/www/html/vendor/dhl/sdk-api-bcs-returns/src/Http/ClientPlugin/ReturnLabelErrorPlugin.php on line 85

Link (master): https://github.com/netresearch/dhl-sdk-api-bcs-returns/blob/master/src/Http/ClientPlugin/ReturnLabelErrorPlugin.php#L85

**What happen:**
The response body seems to be empty.
So `json_decode` will return NULL because it cannot decode.
At `$this->createErrorMessage()` we then provide NULL to an expected array parameter which causes the error.

**Info:**
DHL currently has some error or maintenance on the retoure API 
and i guess they return an empty body.
![image](https://user-images.githubusercontent.com/13582504/225888429-26947ae7-9103-4885-a416-baec9b420384.png)

> Funktion Retoure: Aufgrund eines Fehlers ist die Funktion aktuell nicht aufrufbar. Die Fehlerbehebung ist bereits in Arbeit. Wir bitte um Entschuldigung für die Unannehmlichkeiten.

**Possible solution:** 

    $responseJson = (string)$response->getBody();
    $responseData = \json_decode($responseJson, true);
    if (!is_array($responseData)) {
        // Could not json_decode body.
        // This could be an empty body due to Maintenance at DHL retoure API.
        $responseData = [];
    }
    $errorMessage = $this->createErrorMessage($responseData, $response->getReasonPhrase());

**Comment by mam08ixo** [comment]
Thank you for the report. We will add a type check accordingly in a future version.

**Comment by mam08ixo** [comment]
The issue was fixed in version [2.1.2](https://github.com/netresearch/dhl-sdk-api-bcs-returns/releases/tag/2.1.2) of the package.
